package svl;

# all journal, volume, legal literature keywords
my @journal_keywords = (
"Abgabenordnung \(AO\/FGO\)",
"African Tax Systems",
"Amtliche Sammlung",
"Amtsbericht",
"Amtsblatt",
"Annual Report ....",
"Appenzell A\. Rh\. Verwaltungspraxis",
"Aussensteuerrecht",
"Bereinigte Gesetzessammlung",
"Bericht des Bundesrates zur Aussenwirtschaftspolitik",
"Bericht zum Finanzplan des Bundes",
"Budget ....",
"Budget Basel-Stadt",
"Bundesfinanzen des Bundes",
"Cahiers de Droit Fiscal International",
"Das aktuelle Steuerhandbuch",
"Das schweizerische Energiekonzept\.",
"Der Steuerentscheid",
"Die direkte Bundessteuer \(Wehrsteuer\)",
"Die Eidgenössische Mehrwertsteuer \(....\)",
"Die eidg\. Verrechnungssteuer",
"Die Praxis der Bundessteuern",
"Doppelbesteuerung",
"Droit fiscal international de la Suisse",
"Entscheide der Gerichts- und Verwaltungsbeh.rden", 
"Entscheide der Steuerrekurskommission",
"Entscheidungen des Schweizerischen Bundesgerichts",
"Entwicklung der Realsteuerhebes.tze der Gemeinden",
"Entwicklung wesentlicher Daten der .ffentlichen Finanzwirtschaft",
"European Tax Directory",
"Finanzen der Schweiz",
"Finanzplanung Appenzell Innerrhoden ....",
"Fiskaleinnahmen des Bundes ....",
"Galler Gemeindefinanzen",
"Galler Steuerentscheide",
"Gerichts- und Verwaltungsentscheide",
"Gerichts- und Verwaltungspraxis",
"Gesch.ftsbericht .... der Stadt",
"Gesetzessammlung Neue Reihe",
"Grundsätzliche Entscheide des Solothurnischen Kantonalen Steuergerichts",
"Handbuch der Finanzwissenschaft",
"Handbuch Internationale Verrechnungspreise",
"IFF Referenten- und Autorenforum",
"IFSt-Schrift","IFSt-Brief","IFSt-Heft",
"Internationale Steuern",
"Internationales Steuerrecht der Schweiz",
"Internationales Steuer-Lexikon",
"Jahresbericht ..",
"[j|J]ahrbuch",
"[j|J]ournal",
"Kantonalen Rekurskommission",
"Kantonsfinanzen\/Finances des cantons",
"Kommunale Geb.hrenhaushalte",
"Kommentar zum Einkommensteuergesetz EStG",
"Kommentar zum Z.rcher Steuergesetz",
"Landesplanerische Leitbilder der Schweiz",
"Model Tax Convention on Income and on Capital",
"Orange Tax Guide",
"Praxis des Verwaltungsgerichts", 
"Rechenschaftsbericht",
"Rechnung Basel-Stadt für das Jahr",
"Rechnung .... der Stadt",
"Rechnung .... des Kantons",
"Rechnung für den Staat",
"Sammlung der Entscheidungen des Bundesfinanzhofs",
"Sammlung der Verwaltungsentscheide",
"Schweizerisches Steuer-Lexikon",
"Staatsrechnung ",
"Steuerbelastung in der Schweiz\.",
"St.Galler Seminar .... [.ber|zur] Unternehmungsbesteuerung",
"St.Galler Steuerbuch",
"Swiss-U.S. Income Tax Treaty",
"Taxation and Investment in Central & East European Countries",
"Thurgauische Verwaltungsrechtspflege",
"Umsatzsteuergesetz",
"Verwaltungspraxis der Bundesbeh.rden",
"Verwaltungs- und Verwaltungsgerichtsentscheide",
"Voranschlag",
"Wirtschaft und Finanzen im Ausland",
"[y|Y]earbook", 
"Zwischenstaatliche Belastungs- und Strukturvergleiche",
"Z.rcher Steuerbuch");

my $TITLES = join "|",@journal_keywords;

1;